# Generated by Django 5.2.7 on 2025-11-03 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categorias/",
                        verbose_name="Imagen",
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "db_table": "categoria",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="marcas/", verbose_name="Logo"
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
            ],
            options={
                "verbose_name": "Marca",
                "verbose_name_plural": "Marcas",
                "db_table": "marca",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Talla",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=10, unique=True, verbose_name="Nombre"),
                ),
                ("orden", models.IntegerField(default=0, verbose_name="Orden")),
            ],
            options={
                "verbose_name": "Talla",
                "verbose_name_plural": "Tallas",
                "db_table": "talla",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Prenda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                ("color", models.CharField(max_length=50, verbose_name="Color")),
                (
                    "material",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Material"
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "destacada",
                    models.BooleanField(default=False, verbose_name="Destacada"),
                ),
                (
                    "es_novedad",
                    models.BooleanField(default=False, verbose_name="Es novedad"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=250, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "categorias",
                    models.ManyToManyField(
                        related_name="prendas",
                        to="products.categoria",
                        verbose_name="Categorías",
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prendas",
                        to="products.marca",
                        verbose_name="Marca",
                    ),
                ),
                (
                    "tallas_disponibles",
                    models.ManyToManyField(
                        related_name="prendas",
                        to="products.talla",
                        verbose_name="Tallas disponibles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prenda",
                "verbose_name_plural": "Prendas",
                "db_table": "prenda",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImagenPrenda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(upload_to="productos/", verbose_name="Imagen"),
                ),
                (
                    "es_principal",
                    models.BooleanField(default=False, verbose_name="Es principal"),
                ),
                ("orden", models.IntegerField(default=0, verbose_name="Orden")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Texto alternativo"
                    ),
                ),
                (
                    "prenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="products.prenda",
                        verbose_name="Prenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de Prenda",
                "verbose_name_plural": "Imágenes de Prendas",
                "db_table": "imagen_prenda",
                "ordering": ["orden", "-es_principal"],
                "indexes": [
                    models.Index(
                        fields=["prenda", "orden"],
                        name="imagen_pren_prenda__8818f4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StockPrenda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("cantidad", models.IntegerField(default=0, verbose_name="Cantidad")),
                (
                    "stock_minimo",
                    models.IntegerField(default=5, verbose_name="Stock mínimo"),
                ),
                (
                    "prenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="products.prenda",
                        verbose_name="Prenda",
                    ),
                ),
                (
                    "talla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="products.talla",
                        verbose_name="Talla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock de Prenda",
                "verbose_name_plural": "Stocks de Prendas",
                "db_table": "stock_prenda",
                "indexes": [
                    models.Index(
                        fields=["prenda", "talla"],
                        name="stock_prend_prenda__4de907_idx",
                    )
                ],
                "unique_together": {("prenda", "talla")},
            },
        ),
        migrations.AddIndex(
            model_name="prenda",
            index=models.Index(fields=["slug"], name="prenda_slug_21a732_idx"),
        ),
        migrations.AddIndex(
            model_name="prenda",
            index=models.Index(
                fields=["activa", "-created_at"], name="prenda_activa_7e963f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prenda",
            index=models.Index(
                fields=["destacada", "-created_at"], name="prenda_destaca_90422f_idx"
            ),
        ),
    ]
