# Generated by Django 4.2.7 on 2025-11-11 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MetodoPago",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "requiere_procesador",
                    models.BooleanField(
                        default=False, verbose_name="Requiere procesador externo"
                    ),
                ),
                (
                    "configuracion",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Configuración"
                    ),
                ),
            ],
            options={
                "verbose_name": "Método de Pago",
                "verbose_name_plural": "Métodos de Pago",
                "db_table": "metodo_pago",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "numero_pedido",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Número de pedido",
                    ),
                ),
                (
                    "direccion_snapshot",
                    models.JSONField(default=dict, verbose_name="Datos de dirección"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Subtotal"
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Descuento",
                    ),
                ),
                (
                    "costo_envio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Costo de envío",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de pago"),
                            ("pago_recibido", "Pago recibido"),
                            ("confirmado", "Confirmado"),
                            ("preparando", "Preparando"),
                            ("enviado", "Enviado"),
                            ("entregado", "Entregado"),
                            ("cancelado", "Cancelado"),
                            ("reembolsado", "Reembolsado"),
                        ],
                        default="pendiente",
                        max_length=50,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "notas_cliente",
                    models.TextField(blank=True, verbose_name="Notas del cliente"),
                ),
                (
                    "notas_internas",
                    models.TextField(blank=True, verbose_name="Notas internas"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "direccion_envio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="customers.direccion",
                        verbose_name="Dirección de envío",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "db_table": "pedido",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("procesando", "Procesando"),
                            ("completado", "Completado"),
                            ("fallido", "Fallido"),
                            ("reembolsado", "Reembolsado"),
                        ],
                        default="pendiente",
                        max_length=50,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID de transacción"
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Stripe Payment Intent ID",
                    ),
                ),
                (
                    "paypal_order_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="PayPal Order ID"
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Datos de respuesta"
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "metodo_pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="orders.metodopago",
                        verbose_name="Método de pago",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="orders.pedido",
                        verbose_name="Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "db_table": "pago",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistorialEstadoPedido",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de pago"),
                            ("pago_recibido", "Pago recibido"),
                            ("confirmado", "Confirmado"),
                            ("preparando", "Preparando"),
                            ("enviado", "Enviado"),
                            ("entregado", "Entregado"),
                            ("cancelado", "Cancelado"),
                            ("reembolsado", "Reembolsado"),
                        ],
                        max_length=50,
                        verbose_name="Estado anterior",
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de pago"),
                            ("pago_recibido", "Pago recibido"),
                            ("confirmado", "Confirmado"),
                            ("preparando", "Preparando"),
                            ("enviado", "Enviado"),
                            ("entregado", "Entregado"),
                            ("cancelado", "Cancelado"),
                            ("reembolsado", "Reembolsado"),
                        ],
                        max_length=50,
                        verbose_name="Estado nuevo",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_estados",
                        to="orders.pedido",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "usuario_cambio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cambios_estado_pedido",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que hizo el cambio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Estado",
                "verbose_name_plural": "Historial de Estados",
                "db_table": "historial_estado_pedido",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Envio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "numero_seguimiento",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        unique=True,
                        verbose_name="Número de seguimiento",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("preparando", "Preparando"),
                            ("recogido", "Recogido"),
                            ("en_transito", "En tránsito"),
                            ("entregado", "Entregado"),
                            ("devuelto", "Devuelto"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=50,
                        verbose_name="Estado del envío",
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de envío"
                    ),
                ),
                (
                    "fecha_entrega_estimada",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de entrega estimada"
                    ),
                ),
                (
                    "fecha_entrega_real",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de entrega real"
                    ),
                ),
                (
                    "empresa_transportista",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Empresa transportista"
                    ),
                ),
                (
                    "costo_envio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Costo del envío",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "asignado_a",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"rol__nombre": "Delivery"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="envios_asignados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado a (Delivery)",
                    ),
                ),
                (
                    "pedido",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="envio",
                        to="orders.pedido",
                        verbose_name="Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Envío",
                "verbose_name_plural": "Envíos",
                "db_table": "envio",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio unitario"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Subtotal"
                    ),
                ),
                (
                    "producto_snapshot",
                    models.JSONField(default=dict, verbose_name="Datos del producto"),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="orders.pedido",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "prenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_pedido",
                        to="products.prenda",
                        verbose_name="Prenda",
                    ),
                ),
                (
                    "talla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_pedido",
                        to="products.talla",
                        verbose_name="Talla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Pedido",
                "verbose_name_plural": "Detalles de Pedidos",
                "db_table": "detalle_pedido",
            },
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(
                fields=["usuario", "-created_at"], name="pedido_usuario_621347_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(
                fields=["numero_pedido"], name="pedido_numero__dc4441_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(
                fields=["estado", "-created_at"], name="pedido_estado_590baa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(
                fields=["pedido", "-created_at"], name="pago_pedido__4ba6f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(fields=["estado"], name="pago_estado_e7b4e1_idx"),
        ),
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(
                fields=["transaction_id"], name="pago_transac_9966e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historialestadopedido",
            index=models.Index(
                fields=["pedido", "-created_at"], name="historial_e_pedido__8dca9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="envio",
            index=models.Index(
                fields=["pedido", "-created_at"], name="envio_pedido__83914e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="envio",
            index=models.Index(
                fields=["numero_seguimiento"], name="envio_numero__32bfa1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="envio",
            index=models.Index(
                fields=["estado", "-created_at"], name="envio_estado_9e89b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="envio",
            index=models.Index(
                fields=["asignado_a", "estado"], name="envio_asignad_34acc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detallepedido",
            index=models.Index(
                fields=["pedido", "-created_at"], name="detalle_ped_pedido__a3ea3e_idx"
            ),
        ),
    ]
