# Generated by Django 5.2.7 on 2025-11-09 04:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Direccion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "nombre_completo",
                    models.CharField(max_length=200, verbose_name="Nombre completo"),
                ),
                ("telefono", models.CharField(max_length=20, verbose_name="Teléfono")),
                (
                    "direccion_linea1",
                    models.CharField(max_length=255, verbose_name="Dirección línea 1"),
                ),
                (
                    "direccion_linea2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dirección línea 2"
                    ),
                ),
                ("ciudad", models.CharField(max_length=100, verbose_name="Ciudad")),
                (
                    "departamento",
                    models.CharField(
                        max_length=100, verbose_name="Departamento/Estado"
                    ),
                ),
                (
                    "codigo_postal",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Código postal"
                    ),
                ),
                (
                    "pais",
                    models.CharField(
                        default="Bolivia", max_length=100, verbose_name="País"
                    ),
                ),
                (
                    "referencia",
                    models.TextField(blank=True, verbose_name="Referencias"),
                ),
                (
                    "es_principal",
                    models.BooleanField(default=False, verbose_name="Es principal"),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direcciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dirección",
                "verbose_name_plural": "Direcciones",
                "db_table": "direccion",
                "ordering": ["-es_principal", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "es_principal"],
                        name="direccion_usuario_276736_idx",
                    ),
                    models.Index(
                        fields=["ciudad", "departamento"],
                        name="direccion_ciudad_df017c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Favoritos",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "prenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoritos",
                        to="products.prenda",
                        verbose_name="Prenda",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoritos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorito",
                "verbose_name_plural": "Favoritos",
                "db_table": "favoritos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "-created_at"],
                        name="favoritos_usuario_d7c5bf_idx",
                    )
                ],
                "unique_together": {("usuario", "prenda")},
            },
        ),
    ]
