# Generated by Django 4.2.7 on 2025-11-11 04:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_loginaudit"),
    ]

    operations = [
        # Rename indexes (no DB-type-sensitive change)
        migrations.RenameIndex(
            model_name="loginaudit",
            new_name="login_audit_user_id_8dc54a_idx",
            old_name="login_audit_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="loginaudit",
            new_name="login_audit_created_e28a08_idx",
            old_name="login_audit_created_idx",
        ),

        # Safely migrate bigint primary key -> uuid primary key.
        # Direct casting ("id"::uuid) fails if existing integer values are not valid UUID strings.
        # Approach: create pgcrypto extension (gen_random_uuid), add a new uuid column, populate it,
        # switch primary key, drop old column and rename new column to id. Then update Django's field state.

        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pgcrypto;",
            reverse_sql="-- no-op",
        ),

        # Add a new uuid column with default generator and populate values for existing rows
        migrations.RunSQL(
            sql=(
                "ALTER TABLE login_audit "
                "ADD COLUMN IF NOT EXISTS id_new uuid DEFAULT gen_random_uuid() NOT NULL;"
            ),
            reverse_sql="ALTER TABLE login_audit DROP COLUMN IF EXISTS id_new;",
        ),

        # Ensure every row has a uuid in id_new (gen_random_uuid() default handles new rows, but ensure existing ones)
        migrations.RunSQL(
            sql=(
                "UPDATE login_audit SET id_new = gen_random_uuid() WHERE id_new IS NULL;"
            ),
            reverse_sql="-- no-op",
        ),

        # Swap primary key to id_new. Drop old primary key constraint, create new one on id_new.
        migrations.RunSQL(
            sql=(
                "ALTER TABLE login_audit DROP CONSTRAINT IF EXISTS login_audit_pkey; "
                "ALTER TABLE login_audit ADD PRIMARY KEY (id_new);"
            ),
            reverse_sql=(
                "ALTER TABLE login_audit DROP CONSTRAINT IF EXISTS login_audit_pkey; "
                "-- cannot restore previous bigint PK automatically in reverse"
            ),
        ),

        # Drop old integer id column and rename id_new -> id
        migrations.RunSQL(
            sql=(
                "ALTER TABLE login_audit DROP COLUMN IF EXISTS id; "
                "ALTER TABLE login_audit RENAME COLUMN id_new TO id;"
            ),
            reverse_sql=(
                "-- reverse is not supported for automatic bigint recreation; manual intervention required"
            ),
        ),

        # Reflect the change in Django's state: make id a UUIDField primary key
        migrations.AlterField(
            model_name="loginaudit",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),

        # Minor update to updated_at verbose name (keeps the intended change)
        migrations.AlterField(
            model_name="loginaudit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Última actualización"),
        ),
    ]
