# Generated by Django 4.2.7 on 2025-11-11 17:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del modelo"),
                ),
                ("version", models.CharField(max_length=50, verbose_name="Versión")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "archivo_modelo",
                    models.CharField(
                        max_length=500, verbose_name="Ruta del archivo del modelo"
                    ),
                ),
                (
                    "mae",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Mean Absolute Error"
                    ),
                ),
                (
                    "mse",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Mean Squared Error"
                    ),
                ),
                (
                    "rmse",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Root Mean Squared Error"
                    ),
                ),
                (
                    "r2_score",
                    models.FloatField(blank=True, null=True, verbose_name="R² Score"),
                ),
                (
                    "fecha_entrenamiento",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de entrenamiento"
                    ),
                ),
                (
                    "registros_entrenamiento",
                    models.IntegerField(
                        verbose_name="Registros usados en entrenamiento"
                    ),
                ),
                (
                    "features_utilizadas",
                    models.JSONField(default=list, verbose_name="Features utilizadas"),
                ),
                (
                    "hiperparametros",
                    models.JSONField(default=dict, verbose_name="Hiperparámetros"),
                ),
                (
                    "activo",
                    models.BooleanField(default=False, verbose_name="Modelo activo"),
                ),
                (
                    "notas",
                    models.TextField(blank=True, verbose_name="Notas adicionales"),
                ),
            ],
            options={
                "verbose_name": "Modelo ML",
                "verbose_name_plural": "Modelos ML",
                "db_table": "ml_model",
                "ordering": ["-fecha_entrenamiento"],
            },
        ),
        migrations.CreateModel(
            name="PrediccionVentas",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "fecha_prediccion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de la predicción"
                    ),
                ),
                (
                    "periodo_predicho",
                    models.CharField(
                        max_length=50, verbose_name="Período predicho (ej: 2025-11)"
                    ),
                ),
                (
                    "ventas_predichas",
                    models.FloatField(verbose_name="Ventas predichas"),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Categoría (si aplica)"
                    ),
                ),
                (
                    "producto_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID Producto (si aplica)"
                    ),
                ),
                (
                    "features_input",
                    models.JSONField(default=dict, verbose_name="Features de entrada"),
                ),
                (
                    "ventas_reales",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Ventas reales (para comparar)",
                    ),
                ),
                (
                    "error",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Error de predicción"
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="predicciones",
                        to="ai.mlmodel",
                        verbose_name="Modelo usado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Predicción de Ventas",
                "verbose_name_plural": "Predicciones de Ventas",
                "db_table": "prediccion_ventas",
                "ordering": ["-fecha_prediccion"],
            },
        ),
        migrations.AddIndex(
            model_name="mlmodel",
            index=models.Index(
                fields=["activo", "-fecha_entrenamiento"],
                name="ml_model_activo_d94f04_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mlmodel",
            index=models.Index(fields=["version"], name="ml_model_version_c3e429_idx"),
        ),
        migrations.AddIndex(
            model_name="prediccionventas",
            index=models.Index(
                fields=["-fecha_prediccion"], name="prediccion__fecha_p_2ea44a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prediccionventas",
            index=models.Index(
                fields=["periodo_predicho"], name="prediccion__periodo_14f6d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prediccionventas",
            index=models.Index(
                fields=["categoria"], name="prediccion__categor_ae6e96_idx"
            ),
        ),
    ]
