# Generated by Django 4.2.7 on 2025-11-12 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "order_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Notificaciones de pedidos"
                    ),
                ),
                (
                    "payment_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Notificaciones de pagos"
                    ),
                ),
                (
                    "promotion_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Notificaciones de promociones"
                    ),
                ),
                (
                    "stock_notifications",
                    models.BooleanField(
                        default=False, verbose_name="Notificaciones de stock"
                    ),
                ),
                (
                    "general_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Notificaciones generales"
                    ),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Horas silenciosas habilitadas"
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Inicio horas silenciosas"
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Fin horas silenciosas"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferencia de notificación",
                "verbose_name_plural": "Preferencias de notificaciones",
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                ("body", models.TextField(verbose_name="Cuerpo")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order_created", "Pedido Creado"),
                            ("order_shipped", "Pedido Enviado"),
                            ("order_delivered", "Pedido Entregado"),
                            ("order_cancelled", "Pedido Cancelado"),
                            ("payment_success", "Pago Exitoso"),
                            ("payment_failed", "Pago Fallido"),
                            ("stock_alert", "Alerta de Stock"),
                            ("new_product", "Nuevo Producto"),
                            ("promotion", "Promoción"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="Tipo de notificación",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Datos adicionales"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL de imagen"
                    ),
                ),
                ("is_sent", models.BooleanField(default=False, verbose_name="Enviada")),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de envío"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Leída")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de lectura"
                    ),
                ),
                (
                    "fcm_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Respuesta de FCM"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de error"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_611c58_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "-created_at"],
                        name="notificatio_notific_498289_idx",
                    ),
                    models.Index(
                        fields=["is_read", "-created_at"],
                        name="notificatio_is_read_595d11_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Token FCM"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        default="android",
                        max_length=20,
                        verbose_name="Tipo de dispositivo",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nombre del dispositivo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "last_used",
                    models.DateTimeField(auto_now=True, verbose_name="Último uso"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de dispositivo",
                "verbose_name_plural": "Tokens de dispositivos",
                "db_table": "device_tokens",
                "ordering": ["-last_used"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="device_toke_user_id_e99165_idx",
                    ),
                    models.Index(fields=["token"], name="device_toke_token_e218ea_idx"),
                ],
            },
        ),
    ]
